apiVersion: apps/v1
kind: Deployment
metadata:
  name: grounded-sam-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grounded-sam-api
  template:
    metadata:
      labels:
        app: grounded-sam-api
    spec:
      containers:
      - name: grounded-sam-api
        image: friday0013/grounded-sam-api:v0
        resources:
          limits:
            nvidia.com/gpu: 1 # requesting 1 GPU
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule