apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdapp
  template:
    metadata:
      labels:
        app: sdapp
    spec:
      containers:
      - name: sdapp
        image: friday0013/automatic_api_listen_ext:v1.1
        resources:
          limits:
            nvidia.com/gpu: 1 # requesting 1 GPU
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule